/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motoamigopresentacion;

import com.consultarruta.servicios.mapBox.MapBoxService;
import com.mycompany.motoamigodto.RutaResponseDTO;
import com.mycompany.motoamigodto.SolicitudEntregaDTO;
import javax.swing.JOptionPane;
import com.mycompany.motoamigopresentacion.controladores.ControlSolicitarEntrega;
import java.awt.Color;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;
import panelesUtilerias.PanelHeader;
import panelesUtilerias.PanelRedondeado;

/**
 *
 * @author xiomi
 */
public class FrmPublicarARepartidores extends javax.swing.JFrame {

    private ControlSolicitarEntrega control = ControlSolicitarEntrega.getInstance();
    private SolicitudEntregaDTO solicitud;
    PanelRedondeado panelR;

    public FrmPublicarARepartidores(SolicitudEntregaDTO solicitud) {
        initComponents();
        panelR = new PanelRedondeado(30);
        panelR.setBackground(Color.red);
        panelR.setBounds(50, 150, 700, 300);
        setLocationRelativeTo(null);
        add(panelR);

        panPrincipal.setLayout(new AbsoluteLayout());
        panPrincipal.add(new PanelHeader(), new AbsoluteConstraints(0, 0, 1366, 130));
        cargarSolicitud(solicitud);
    }

    public void cargarSolicitud(SolicitudEntregaDTO solicitud) {
        this.solicitud = solicitud;

        txt_origen.setText(solicitud.getOrigen());
        txt_destino.setText(solicitud.getDestino());
        txt_tipoPaquete.setText(solicitud.getTipoPaquete());
        txt_peso.setText(String.valueOf(solicitud.getPesoAprox()));
        txt_ganancia.setText(String.valueOf(solicitud.getDistancia()));
        txt_ganancia.setText(String.valueOf(solicitud.getDistancia() * 10));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        panPrincipal = new javax.swing.JPanel();
        panelRedondeado1 = new panelesUtilerias.PanelRedondeado();
        jLabel11 = new javax.swing.JLabel();
        txt_distancia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_ganancia = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        panelDestino = new panelesUtilerias.PanelRedondeado();
        txt_destino = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelRecoleccion = new panelesUtilerias.PanelRedondeado();
        txt_origen = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelTipoPaquete = new panelesUtilerias.PanelRedondeado();
        txt_tipoPaquete = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelPeso = new panelesUtilerias.PanelRedondeado();
        txt_peso = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solicitud de Entrega");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1008, 738));
        setMinimumSize(new java.awt.Dimension(1008, 738));
        setPreferredSize(new java.awt.Dimension(1023, 738));
        setResizable(false);

        panelRedondeado1.setColorBorde(new java.awt.Color(253, 254, 254));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("DISTANCIA");

        txt_distancia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_distancia.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("GANANCIA");
        jLabel2.setToolTipText("");

        txt_ganancia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_ganancia.setForeground(new java.awt.Color(245, 74, 0));
        txt_ganancia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_aceptar.setBackground(new java.awt.Color(0, 0, 0));
        btn_aceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_aceptar.setForeground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setText("ACEPTAR PEDIDO");
        btn_aceptar.setBorder(null);
        btn_aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        panelDestino.setColorBorde(new java.awt.Color(255, 255, 255));
        panelDestino.setColorFondo(new java.awt.Color(248, 250, 252));
        panelDestino.setPreferredSize(new java.awt.Dimension(890, 80));

        txt_destino.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_destino.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("DESTINO");

        javax.swing.GroupLayout panelDestinoLayout = new javax.swing.GroupLayout(panelDestino);
        panelDestino.setLayout(panelDestinoLayout);
        panelDestinoLayout.setHorizontalGroup(
            panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDestinoLayout.setVerticalGroup(
            panelDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDestinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_destino, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panelRecoleccion.setColorBorde(new java.awt.Color(255, 255, 255));
        panelRecoleccion.setColorFondo(new java.awt.Color(248, 250, 252));
        panelRecoleccion.setPreferredSize(new java.awt.Dimension(890, 80));

        txt_origen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_origen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("RECOLECCION");

        javax.swing.GroupLayout panelRecoleccionLayout = new javax.swing.GroupLayout(panelRecoleccion);
        panelRecoleccion.setLayout(panelRecoleccionLayout);
        panelRecoleccionLayout.setHorizontalGroup(
            panelRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecoleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRecoleccionLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_origen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRecoleccionLayout.setVerticalGroup(
            panelRecoleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecoleccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_origen, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panelTipoPaquete.setColorBorde(new java.awt.Color(255, 255, 255));
        panelTipoPaquete.setColorFondo(new java.awt.Color(248, 250, 252));

        txt_tipoPaquete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_tipoPaquete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("TIPO");

        javax.swing.GroupLayout panelTipoPaqueteLayout = new javax.swing.GroupLayout(panelTipoPaquete);
        panelTipoPaquete.setLayout(panelTipoPaqueteLayout);
        panelTipoPaqueteLayout.setHorizontalGroup(
            panelTipoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTipoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        panelTipoPaqueteLayout.setVerticalGroup(
            panelTipoPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipoPaqueteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelPeso.setColorBorde(new java.awt.Color(255, 255, 255));
        panelPeso.setColorFondo(new java.awt.Color(248, 250, 252));

        txt_peso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_peso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("PESO");

        javax.swing.GroupLayout panelPesoLayout = new javax.swing.GroupLayout(panelPeso);
        panelPeso.setLayout(panelPesoLayout);
        panelPesoLayout.setHorizontalGroup(
            panelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        panelPesoLayout.setVerticalGroup(
            panelPesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRedondeado1Layout = new javax.swing.GroupLayout(panelRedondeado1);
        panelRedondeado1.setLayout(panelRedondeado1Layout);
        panelRedondeado1Layout.setHorizontalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRedondeado1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(panelRedondeado1Layout.createSequentialGroup()
                        .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                                .addComponent(panelTipoPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                            .addComponent(panelRecoleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(panelRedondeado1Layout.createSequentialGroup()
                        .addComponent(txt_distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(97, 97, 97))))
        );
        panelRedondeado1Layout.setVerticalGroup(
            panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_distancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRedondeado1Layout.createSequentialGroup()
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelRecoleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRedondeado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTipoPaquete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPeso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRedondeado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPrincipalLayout.createSequentialGroup()
                .addGap(0, 88, Short.MAX_VALUE)
                .addComponent(panelRedondeado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(panPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed

        boolean resultado = control.publicarSolicitud(solicitud);

        if (resultado) {
            RutaResponseDTO rutaReal = MapBoxService.getInstance()
                .obtenerRuta(solicitud.getOrigen(), solicitud.getDestino());

            if (rutaReal != null) {
                JOptionPane.showMessageDialog(this, "Pedido aceptado. Iniciando navegación.");

                FrmSeguimientoEnTiempoReal seguimiento = new FrmSeguimientoEnTiempoReal(rutaReal);
                seguimiento.setVisible(true);

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al trazar la ruta técnica.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo aceptar el pedido.");
        }

    }//GEN-LAST:event_btn_aceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel panPrincipal;
    private panelesUtilerias.PanelRedondeado panelDestino;
    private panelesUtilerias.PanelRedondeado panelPeso;
    private panelesUtilerias.PanelRedondeado panelRecoleccion;
    private panelesUtilerias.PanelRedondeado panelRedondeado1;
    private panelesUtilerias.PanelRedondeado panelTipoPaquete;
    private javax.swing.JLabel txt_destino;
    private javax.swing.JLabel txt_distancia;
    private javax.swing.JLabel txt_ganancia;
    private javax.swing.JLabel txt_origen;
    private javax.swing.JLabel txt_peso;
    private javax.swing.JLabel txt_tipoPaquete;
    // End of variables declaration//GEN-END:variables
}
