package com.mycompany.motoamigopresentacion;

import com.mycompany.motoamigodto.RutaRequestDTO;
import com.mycompany.motoamigodto.SolicitudEntregaDTO;
import javax.swing.JOptionPane;
import com.mycompany.motoamigopresentacion.controladores.ControlPublicarRepartidores;
import java.awt.Color;

/**
 *
 * @author xiomi
 */
public class FrmPublicarARepartidores_vistaEmprendedor extends javax.swing.JFrame {

    private ControlPublicarRepartidores control = new ControlPublicarRepartidores();

    public FrmPublicarARepartidores_vistaEmprendedor() {
        initComponents();
        Color bg = new Color(248, 250, 252);
        this.getContentPane().setBackground(bg);
    }

    public void cargarSolicitud() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_destino = new javax.swing.JTextField();
        txt_origen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_caja_paquete = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_peso = new javax.swing.JTextField();
        btn_solicitar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_sobre_doc = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solicitud de Entrega");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("DETALLE PEDIDO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("PUNTO DE RECOLECCIÓN *");

        txt_destino.setForeground(new java.awt.Color(102, 102, 102));
        txt_destino.setText("Ej. Calle Nainari 316");

        txt_origen.setForeground(new java.awt.Color(102, 102, 102));
        txt_origen.setText("Ej. Av. Guerrero 550");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("PUNTO DE ENTREGA * ");

        txt_caja_paquete.setEditable(false);
        txt_caja_paquete.setBackground(new java.awt.Color(255, 247, 237));
        txt_caja_paquete.setColumns(5);
        txt_caja_paquete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_caja_paquete.setForeground(new java.awt.Color(255, 105, 0));
        txt_caja_paquete.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_caja_paquete.setText("Caja/Paquete");
        txt_caja_paquete.setToolTipText("");
        txt_caja_paquete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 105, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("PESO APROXIMADO (KG) *");

        txt_peso.setColumns(3);
        txt_peso.setForeground(new java.awt.Color(102, 102, 102));
        txt_peso.setText("0.0");

        btn_solicitar.setBackground(new java.awt.Color(0, 0, 0));
        btn_solicitar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_solicitar.setForeground(new java.awt.Color(255, 255, 255));
        btn_solicitar.setText("VALIDARD DATOS");
        btn_solicitar.setToolTipText("");
        btn_solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MotoAmigo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nueva Solicitud");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15))
        );

        txt_sobre_doc.setEditable(false);
        txt_sobre_doc.setBackground(new java.awt.Color(255, 247, 237));
        txt_sobre_doc.setColumns(5);
        txt_sobre_doc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_sobre_doc.setForeground(new java.awt.Color(255, 105, 0));
        txt_sobre_doc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_sobre_doc.setText("Sobre/Doc");
        txt_sobre_doc.setToolTipText("");
        txt_sobre_doc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 105, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(155, 155, 155)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(txt_caja_paquete, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(92, 92, 92)
                            .addComponent(txt_sobre_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_destino, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_peso)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_caja_paquete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sobre_doc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btn_solicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitarActionPerformed
        // TODO add your handling code here:
        SolicitudEntregaDTO solicitudMock = new SolicitudEntregaDTO(
                // origen
                "Reforma 123",
                // destino
                "Polanco 45",
                // tipoPaquete
                "Caja",
                // pesoAprox
                2.5,
                // idEmprendedor
                1,
                // idEnvio
                101,
                // estado
                "pendiente",
                // distancia
                3.2
        );
        boolean resultado = control.publicarSolicitud(solicitudMock);

        if (resultado) {

            RutaRequestDTO mockRequest = new RutaRequestDTO(
                    "Av. Universidad 123, Ciudad Obregón",
                    "Calle Morelos 456, Ciudad Obregón"
            );
            FrmConsultarRuta frame = new FrmConsultarRuta(mockRequest);
            frame.setVisible(resultado);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo publicar la solicitud. Intenta de nuevo.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_solicitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_solicitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_caja_paquete;
    private javax.swing.JTextField txt_destino;
    private javax.swing.JTextField txt_origen;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_sobre_doc;
    // End of variables declaration//GEN-END:variables
}
